model_list:
 - model_name: gpt-3.5-turbo
   litellm_params: 
      model: "gpt-3.5-turbo"
      api_key: os.environ/OPENAI_API_KEY
 - model_name: gpt-4-0125-preview
   litellm_params:
      model: "gpt-4-0125-preview"
      api_key: os.environ/OPENAI_API_KEY
 - model_name: gpt-4-turbo-preview
   litellm_params:
      model: "gpt-4-turbo-preview"
      api_key: os.environ/OPENAI_API_KEY
 - model_name: gpt-4-1106-preview
   litellm_params:
      model: "gpt-4-1106-preview"
      api_key: os.environ/OPENAI_API_KEY
 - model_name: gpt-4-vision-preview
   litellm_params:
      model: "gpt-4-vision-preview"
      api_key: os.environ/OPENAI_API_KEY
 - model_name: gpt-4-1106-vision-preview
   litellm_params:
      model: "gpt-4-1106-vision-preview"
      api_key: os.environ/OPENAI_API_KEY
 - model_name: gpt-4
   litellm_params:
      model: "gpt-4"
      api_key: os.environ/OPENAI_API_KEY
 - model_name: gpt-4-0613
   litellm_params:
      model: "gpt-4-0613"
      api_key: os.environ/OPENAI_API_KEY
 - model_name: gpt-4-32k
   litellm_params:
      model: "gpt-4-32k"
      api_key: os.environ/OPENAI_API_KEY
 - model_name: gpt-4-32k-0613
   litellm_params:
      model: "gpt-4-32k-0613"
      api_key: os.environ/OPENAI_API_KEY

